apiVersion: v1
kind: Namespace
metadata:
  name: direct-to-pod-pattern-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: direct-to-pod-pattern
  namespace: direct-to-pod-pattern-ns
spec:
  containers:
  - name: green-led
    image: docker.local/gpio/button-plus-led
    args: ["--button", "GPIO27", "--led", "GPIO17"]
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /dev/gpiomem
        name: gpiomem
      - mountPath: /sys
        name: sys
  - name: blue-led
      image: docker.local/gpio/button-plus-led
      args: ["--button", "GPIO27", "--led", "GPIO16"]
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /dev/gpiomem
          name: gpiomem
        - mountPath: /sys
          name: sys
  volumes:
    - name: gpiomem
      hostPath:
        path: /dev/gpiomem
        type: CharDevice
    - name: sys
      hostPath:
        path: /sys
        type: Directory